default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  host: 127.0.0.1
  port: 5432
  username: <%= ENV.fetch("PGUSER") { `whoami`.strip } %>
  database: pennylane_technical_test_development

test:
  <<: *default
  host: 127.0.0.1
  port: 5432
  username: <%= ENV.fetch("PGUSER") { `whoami`.strip } %>
  database: pennylane_technical_test_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

storage:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>