default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  host: 127.0.0.1
  port: 5432
  username: <%= ENV.fetch("PGUSER") { `whoami`.strip } %>
  database: pennylane_technical_test_development

test:
  <<: *default
  host: 127.0.0.1
  port: 5432
  username: <%= ENV.fetch("PGUSER") { `whoami`.strip } %>
  database: pennylane_technical_test_test

production:
  <<: *default
  # Fly va injecter DATABASE_URL quand tu "attach" la base Postgres.
  # Quand DATABASE_URL est présent, Rails l'utilise directement.
  url: <%= ENV["DATABASE_URL"] %>
